### ISSUE TITLE
Use AutoMapper instead of create mapping code

### ISSUE THREAD

**Issue by michaelschnyder** [jobbrIO/jobbr-server#1]
I started with creating some mapping code and that gets a very annoying and repetitive, error prone task. I quickly recalled our discussion regarding AutoMapper and the risks of Convention-over-Configuration when properties get's renamed, etc. There would be a way to validate Profiles but the IgnoreAllNonExisting extension basicallc bypasses this.

Our goal is to fail fast if anything in the models changes i.e.
* TypeChange
* Rename
* Additional Property 
* Removed Property

As far as i understand the IgnoreAllNonExisting extension is not supported anymore (>5.0.0) but there is still the configuration validation feature. https://github.com/AutoMapper/AutoMapper/wiki/Configuration-validation: "AutoMapper checks to make sure that every single Destination type member has a corresponding type member on the source type."

We would need to run tests for all known model-combinations and will be fine, right? That said, we need to decide between the two cases
* Missing TestCase for a Mapping (Origin->Dest, Dest->Origin) of a Type
* Missing mapping for a single property when using a hand-crafterd mapper.

The first case is very unlikely since the model in use will be under test of a unitest where as in some rare cases a property is not tested fullstack.

You oppinion @olibanjoli?

**Comment by olibanjoli** [comment]
Althought i'm not a big fan of AutoMapper I don't mind using AutoMapper as long as we leverage the automapping feature and prevent ourselves from making boilerplate code in straight 1:1 assignments in mapping code.
