### ISSUE TITLE
Create a nice looking logo

### ISSUE THREAD

**Issue by michaelschnyder** [jobbrIO/jobbr-server#24]
maybe @ChristianMoser can help out here?

**Comment by ChristianMoser** [comment]
I will send you sone proposals by e-mail...

**Comment by michaelschnyder** [comment]
Next steps:
- [ ] Define logo formats and store sources and rendered versions in repo
- [ ] set logo in nuget packages (different logos for main and Cm packages)

**Comment by michaelschnyder** [comment]
logos and source files are stored in JobbrIO/artwork
