### ISSUE TITLE
ActualStartDateTimeUtc is null sometimes (migrated)

### ISSUE THREAD

**Issue by michaelschnyder** [jobbrIO/jobbr-server#26]
Issue was migrated from the original jobbr repo and relates to jobbr version < 1.0.0 but might still be an issue. Originally posted by @peitor on Mar 7, 2016:

-----------
It seems like that "ActualStartDateTimeUtc" gets overridden with "Null" by something.

In State: "Started" it seems to be fine.
After "Processing" ... sometimes its "Null"

StartDateTime Null
![image](https://cloud.githubusercontent.com/assets/6833072/24366689/2166867c-131a-11e7-8d50-0c9e003277d4.png)

Over time screenshots
![image](https://cloud.githubusercontent.com/assets/6833072/24365970/fb658d94-1317-11e7-9fac-e5f928740055.png)

**Comment by olibanjoli** [comment]
fixed
