### ISSUE TITLE
Print Assembly versions on server start

### ISSUE THREAD

**Issue by michaelschnyder** [jobbrIO/jobbr-server#3]
I suggest to print out the related versions of loaded assemblies on start
* Jobbr.Server
* Jobbr.Storage Providers
* Any additional Components Like
  * WebAPI
  * ForkedExecution

**Comment by michaelschnyder** [comment]
Blocked by #2

**Comment by olibanjoli** [comment]
a3c914dc2573bba86afb0ecbff890645a56422a6
