### ISSUE TITLE
Create a nice web interface (dashboard) (migrated)

### ISSUE THREAD

**Issue by michaelschnyder** [jobbrIO/jobbr-server#34]
originally proposed by @peitor on Mar 11, 2015 on the old repo

------------
_no description provided_

**Comment by michaelschnyder** [comment]
implementing this should be much easier now, please head off to https://github.com/jobbrIO/jobbr-cm-management for the currently supported management api and https://github.com/jobbrIO/jobbr-cm-registration.

Both repositories are available on NuGet and implemented in the JobbrServer. This is the way how extensions to Jobbr can be built

**Comment by eXpl0it3r** [comment]
Given the Jobbr Dashboard, is this issue still relevant? 
https://github.com/jobbrIO/jobbr-dashboard

**Comment by olibanjoli** [comment]
Nope :)
