### ISSUE TITLE
CM: Make updates to jobstore more specific to avoid lost-updates

### ISSUE THREAD

**Issue by michaelschnyder** [jobbrIO/jobbr-server#35]
We're currently using the `Update()`-Method for JobRuns quite often. Often only to update a small set of properties. I suggest to remove the generic method and instead add an update method that can handle one or multiple `PatchRequests`

@olibanjoli shall we try to include that now or later?

Potentially relates to #26

**Comment by olibanjoli** [comment]
This has been addressed by separating the UpdateProgress Method out of the usual update jobrun
