### ISSUE TITLE
Answer in docu / Readme why another job Server?

### ISSUE THREAD

**Issue by peitor** [jobbrIO/jobbr-server#39]
why another job Server?
Hangfire, Quartz,... where is the difference?

**Comment by michaelschnyder** [comment]
sure. will be a topic in this repository ;)

**Comment by michaelschnyder** [comment]
* Stability & Reliability
* Extendability (WebAPI, Forked Execution, Storage Adapters)
* Clean Architecture (Testability, InMemory, ...)
* No static dependencies to JobServer and Execution Engine
* Automatic persistence of Jobresults (Files)

Differentiation to other FW
* JobServer vs. Scheduler
* Offloader vs. JobServer

**Comment by michaelschnyder** [comment]
here is a first version: http://jobbr.readthedocs.io/en/latest/intro/welcome.html#why-another-jobserver

**Comment by michaelschnyder** [comment]
To be reviewed by @olibanjoli
