### ISSUE TITLE
[Dashboard] Job View: Navigation to see all runs of Job

### ISSUE THREAD

**Issue by eXpl0it3r** [jobbrIO/jobbr-server#69]
When you're on a Job (e.g. /jobs/2), you only get to see the last 10 runs (which is useful), but there's no easy navigation point to see all runs of a certain job.

A button to navigate to the /runs/ tab with the job name set as filter might be quite useful.

Current workaround:

- Click on Runs
- Enter the Job name manually

**Comment by olibanjoli** [comment]
I added an own jobruns page within jobdetail since filtering by jobname is a bit hacky.

https://github.com/jobbrIO/jobbr-dashboard/commit/5498693358a581d190cdc2bad9bd7cf81eb04327

I have to fix a warning in the nuspec file. Ill fix that later this evening and publish a nuget.

cheers
